version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/opt/taia-x/frontend:cached
      - /opt/taia-x/frontend/node_modules
    container_name: taia-x-frontend
    environment:
      - CHOKIDAR_INTERVAL=1000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:8080

  compile-contracts:
    image: ligolang/ligo:0.32.0
    container_name: taia-compile-smart-contracts  
    platform: linux/amd64
    volumes:
      - ./contracts/:/opt/taia-x/contracts
    command: "compile contract ${SOURCE_FILE} --entry-point ${ENTRY_POINT} -o ${OUTPUT_FILE}"  

  deploy-sandbox: 
    image: node:8
    container_name: taia-deploy-on-sandbox
    platform: linux/amd64
    working_dir: ./contracts
    environment:
      - NODE_ENV=production
    volumes:
      - ./contracts/scripts:/opt/taia-x/contracts/scripts
    command: node deploy.js sandbox

  sandbox:
    image: tqtezos/flextesa:20211206
    volumes:
      - mini-box:/tmp/mini-box
    container_name: taia-x-sandbox
    environment:
      block_time: 1
      flextesa_node_cors_origin: "*"
    command: "granabox start --keep-root"
    ports:
      - 20000:20000

  # to build a ipfs cluster: https://github.com/ipfs/ipfs-cluster/blob/master/docker-compose.yml
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8081:8080 # ipfs gateway - expose if needed/wanted
      # - 4001:4001 # ipfs swarm - expose if needed/wanted
    volumes:
      - ipfsf:/data/ipfs
    container_name: taia-x-ipfs

volumes:
  ipfsf:
  mini-box:
