version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/opt/taia-x/frontend:cached
      - /opt/taia-x/frontend/node_modules
    container_name: taia-x-frontend
    environment:
      - CHOKIDAR_INTERVAL=1000
    ports:
      - 8080:8080

  compile-contracts:
    image: ligolang/ligo:0.32.0
    container_name: taia-compile-smart-contracts  
    platform: linux/amd64
    volumes:
      - ./contracts/:/opt/taia-x/contracts
    command: "compile contract ${SOURCE_FILE} --entry-point ${ENTRY_POINT} -o ${OUTPUT_FILE}"  

  sandbox:
    image: tqtezos/flextesa:20210514
    container_name: taia-x-sandbox
    environment:
      block_time: 1
      flextesa_node_cors_origin: "*"
    command: "flobox start --keep-root"
    ports:
      - 20000:20000

  # to build a ipfs cluster: https://github.com/ipfs/ipfs-cluster/blob/master/docker-compose.yml
  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    ports:
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8081:8080 # ipfs gateway - expose if needed/wanted
      # - 4001:4001 # ipfs swarm - expose if needed/wanted
    volumes:
      - ipfsf:/data/ipfs

volumes:
  ipfsf:
