version: "3.4"

services:
  backend:
    container_name: taia-x-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - taia-x
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-dipdup}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_HOST=${POSTGRES_HOST:-db_dipdup}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-dipdup}
    volumes:
      - ./:/backend/
    entrypoint: ./docker-start.sh
    ports:
      - 5678:5678
      - 8000:8000

networks:
  taia-x:
    name: taia-x
