version: "3.4"

services:
  db_tzkt:
    container_name: tzkt-db
    networks:
      - taia-x
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
    expose:
      - 5432
    ports:
      - 0.0.0.0:5432:5432

  api_tzkt:
    container_name: tzkt-api
    networks:
      - taia-x
    restart: always
    image: bakingbad/tzkt-api:1.6.4
    depends_on:
      - db_tzkt
    environment:
      TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://0.0.0.0:5000
      TZKT_API_ConnectionStrings__DefaultConnection: host=db_tzkt;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
    expose:
      - 5000
    ports:
      - 0.0.0.0:5000:5000

  sync_tzkt:
    container_name: tzkt-sync
    networks:
      - taia-x
    restart: always
    image: bakingbad/tzkt-sync:1.6.4
    environment:
      TZKT_TezosNode__Endpoint: http://sandbox:20000
      TZKT_ConnectionStrings__DefaultConnection: host=db_tzkt;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
    depends_on:
      - db_tzkt

networks:
  taia-x:
    name: taia-x
