version: "3.4"

services:
  # to build a ipfs cluster: https://github.com/ipfs/ipfs-cluster/blob/master/docker-compose.yml
  ipfs:
    image: ipfs/go-ipfs:latest
    networks:
      - taia-x
    ports:
      - 127.0.0.1:5001:5001 # ipfs api
      - 127.0.0.1:8081:8080 # ipfs gateway
      - 4001:4001 # ipfs swarm - expose if needed/wanted
    volumes:
      - ipfsf:/data/ipfs
    container_name: taia-x-ipfs

volumes:
  ipfsf:

networks:
  taia-x:
    name: taia-x
