name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-provider:
    name: Run tests

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f provider/requirements.txt ]; then pip install -r provider/requirements.txt; fi

      - name: Run tests
        run: |
          pytest