name: Tests

on: [push, pull_request]

jobs:
  test-provider:
    name: Run tests

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [3.9.7]

    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
          with:
            python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: cd provider & pip install -r requirements.txt

      - name: Run tests
        run: cd provider & pytest