name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [16.13]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Run tests
      run: |
        cd frontend
        npm ci
        npm run lint
        npm run test:unit
      env:
        CI: true